"""Type stubs for hb_zayfer._native (Rust PyO3 bindings)."""

from __future__ import annotations


def version() -> str: ...

# -- Symmetric: AES-256-GCM --
def aes_encrypt(key: bytes, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes]: ...
def aes_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

# -- Symmetric: ChaCha20-Poly1305 --
def chacha_encrypt(key: bytes, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes]: ...
def chacha_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

# -- KDF --
def generate_salt(length: int) -> bytes: ...
def derive_key_argon2(
    passphrase: bytes,
    salt: bytes,
    m_cost: int = 65536,
    t_cost: int = 3,
    p_cost: int = 1,
) -> bytes: ...
def derive_key_scrypt(
    passphrase: bytes,
    salt: bytes,
    log_n: int = 15,
    r: int = 8,
    p: int = 1,
) -> bytes: ...

# -- RSA --
def rsa_generate(bits: int) -> tuple[str, str]: ...
def rsa_encrypt(public_pem: str, plaintext: bytes) -> bytes: ...
def rsa_decrypt(private_pem: str, ciphertext: bytes) -> bytes: ...
def rsa_sign(private_pem: str, message: bytes) -> bytes: ...
def rsa_verify(public_pem: str, message: bytes, signature: bytes) -> bool: ...
def rsa_fingerprint(public_pem: str) -> str: ...

# -- Ed25519 --
def ed25519_generate() -> tuple[str, str]: ...
def ed25519_sign(signing_pem: str, message: bytes) -> bytes: ...
def ed25519_verify(verifying_pem: str, message: bytes, signature: bytes) -> bool: ...
def ed25519_fingerprint(verifying_pem: str) -> str: ...

# -- X25519 --
def x25519_generate() -> tuple[bytes, bytes]: ...
def x25519_encrypt_key_agreement(their_public: bytes) -> tuple[bytes, bytes]: ...
def x25519_decrypt_key_agreement(secret_raw: bytes, ephemeral_public: bytes) -> bytes: ...
def x25519_fingerprint(public_raw: bytes) -> str: ...

# -- OpenPGP --
def pgp_generate(user_id: str) -> tuple[str, str]: ...
def pgp_encrypt(plaintext: bytes, recipient_public_keys: list[str]) -> bytes: ...
def pgp_decrypt(ciphertext: bytes, secret_key_armored: str) -> bytes: ...
def pgp_sign(message: bytes, secret_key_armored: str) -> bytes: ...
def pgp_verify(signed_message: bytes, public_key_armored: str) -> tuple[bytes, bool]: ...
def pgp_fingerprint(armored_key: str) -> str: ...
def pgp_user_id(armored_key: str) -> str | None: ...

# -- HBZF file encryption --
def encrypt_data(
    plaintext: bytes,
    algorithm: str = "aes",
    wrapping: str = "password",
    passphrase: bytes | None = None,
    recipient_public_pem: str | None = None,
    recipient_public_raw: bytes | None = None,
    kdf: str = "argon2id",
    kdf_memory_kib: int | None = None,
    kdf_iterations: int | None = None,
    kdf_log_n: int | None = None,
    kdf_r: int | None = None,
    kdf_p: int | None = None,
) -> bytes: ...
def decrypt_data(
    data: bytes,
    passphrase: bytes | None = None,
    private_pem: str | None = None,
    secret_raw: bytes | None = None,
) -> bytes: ...
def encrypt_file(
    input_path: str,
    output_path: str,
    algorithm: str = "aes",
    wrapping: str = "password",
    passphrase: bytes | None = None,
    recipient_public_pem: str | None = None,
    recipient_public_raw: bytes | None = None,
    kdf: str = "argon2id",
    kdf_memory_kib: int | None = None,
    kdf_iterations: int | None = None,
    kdf_log_n: int | None = None,
    kdf_r: int | None = None,
    kdf_p: int | None = None,
) -> int: ...
def decrypt_file(
    input_path: str,
    output_path: str,
    passphrase: bytes | None = None,
    private_pem: str | None = None,
    secret_raw: bytes | None = None,
) -> int: ...

# -- Utilities --
def compute_fingerprint(public_key_bytes: bytes) -> str: ...
def detect_key_format(data: bytes) -> str: ...

# -- Password generation --
def generate_password(
    length: int = 20,
    uppercase: bool = True,
    lowercase: bool = True,
    digits: bool = True,
    symbols: bool = True,
    exclude: str = "",
) -> str: ...
def generate_passphrase(words: int = 6, separator: str = "-") -> str: ...
def password_entropy(
    length: int = 20,
    uppercase: bool = True,
    lowercase: bool = True,
    digits: bool = True,
    symbols: bool = True,
) -> float: ...
def passphrase_entropy(word_count: int = 6) -> float: ...

# -- Shamir's Secret Sharing --
def shamir_split(secret: bytes, n: int, k: int) -> list[str]: ...
def shamir_combine(shares_hex: list[str]) -> bytes: ...

# -- Steganography --
def stego_embed(pixels: bytes, payload: bytes) -> bytes: ...
def stego_extract(pixels: bytes) -> bytes: ...
def stego_capacity(pixel_len: int) -> int: ...

# -- Secure file shredding --
def shred_file(path: str, passes: int = 3) -> None: ...
def shred_directory(path: str, passes: int = 3) -> int: ...

# -- QR key exchange --
def qr_encode_key_uri(algorithm: str, public_key: bytes, label: str | None = None) -> str: ...
def qr_decode_key_uri(uri: str) -> tuple[str, bytes, str | None]: ...

# -- Audit logging --
def audit_log_key_generated(algorithm: str, fingerprint: str, note: str | None = None) -> None: ...
def audit_log_file_encrypted(
    algorithm: str,
    filename: str | None = None,
    size_bytes: int | None = None,
    note: str | None = None,
) -> None: ...
def audit_log_file_decrypted(
    algorithm: str,
    filename: str | None = None,
    size_bytes: int | None = None,
    note: str | None = None,
) -> None: ...
def audit_log_data_signed(algorithm: str, fingerprint: str, note: str | None = None) -> None: ...
def audit_log_signature_verified(
    algorithm: str,
    fingerprint: str,
    valid: bool,
    note: str | None = None,
) -> None: ...
def audit_log_contact_added(name: str, note: str | None = None) -> None: ...
def audit_log_contact_deleted(name: str, note: str | None = None) -> None: ...
def audit_log_key_deleted(fingerprint: str, note: str | None = None) -> None: ...

# -- Classes --
class KeyMetadata:
    fingerprint: str
    algorithm: str
    label: str
    created_at: str
    has_private: bool
    has_public: bool
    def __repr__(self) -> str: ...

class Contact:
    name: str
    email: str | None
    key_fingerprints: list[str]
    notes: str | None
    created_at: str
    def __repr__(self) -> str: ...

class KeyStore:
    def __init__(self, path: str | None = None) -> None: ...
    @property
    def base_path(self) -> str: ...
    def store_private_key(
        self,
        fingerprint: str,
        key_bytes: bytes,
        passphrase: bytes,
        algorithm: str,
        label: str,
    ) -> None: ...
    def store_public_key(
        self,
        fingerprint: str,
        key_bytes: bytes,
        algorithm: str,
        label: str,
    ) -> None: ...
    def load_private_key(self, fingerprint: str, passphrase: bytes) -> bytes: ...
    def load_public_key(self, fingerprint: str) -> bytes: ...
    def list_keys(self) -> list[KeyMetadata]: ...
    def get_key_metadata(self, fingerprint: str) -> KeyMetadata | None: ...
    def find_keys_by_label(self, query: str) -> list[KeyMetadata]: ...
    def delete_key(self, fingerprint: str) -> None: ...
    def add_contact(
        self,
        name: str,
        email: str | None = None,
        notes: str | None = None,
    ) -> None: ...
    def associate_key_with_contact(self, contact_name: str, fingerprint: str) -> None: ...
    def get_contact(self, name: str) -> Contact | None: ...
    def list_contacts(self) -> list[Contact]: ...
    def remove_contact(self, name: str) -> None: ...
    def update_contact(
        self,
        name: str,
        email: str | None = None,
        notes: str | None = None,
    ) -> None: ...
    def resolve_recipient(self, name_or_fp: str) -> list[str]: ...
    def create_backup(self, output_path: str, passphrase: bytes, label: str | None = None) -> None: ...
    def restore_backup(self, backup_path: str, passphrase: bytes) -> BackupManifest: ...
    def verify_backup(self, backup_path: str, passphrase: bytes) -> BackupManifest: ...

class BackupManifest:
    created_at: str
    private_key_count: int
    public_key_count: int
    contact_count: int
    version: int
    label: str | None
    integrity_hash: str

class AuditEntry:
    timestamp: str
    operation: str
    prev_hash: str | None
    entry_hash: str
    note: str | None

class AuditLogger:
    def __init__(self, path: str | None = None) -> None: ...
    def recent_entries(self, limit: int = 20) -> list[AuditEntry]: ...
    def verify_integrity(self) -> bool: ...
    def export(self, destination: str) -> None: ...
    def entry_count(self) -> int: ...

# -- Typed exceptions (subclass familiar built-ins for backward compatibility) --
class ZayferError(RuntimeError): ...
class AuthenticationError(PermissionError): ...
class KeyNotFoundError(FileNotFoundError): ...
class ContactNotFoundError(FileNotFoundError): ...
class IntegrityError(ValueError): ...
class KeyAlreadyExistsError(ValueError): ...
class ContactAlreadyExistsError(ValueError): ...
