"""Type stubs for hb_zayfer._native (Rust PyO3 bindings)."""

from __future__ import annotations

from typing import Optional

def version() -> str: ...

# -- Symmetric: AES-256-GCM --
def aes_encrypt(key: bytes, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes]: ...
def aes_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

# -- Symmetric: ChaCha20-Poly1305 --
def chacha_encrypt(key: bytes, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes]: ...
def chacha_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

# -- KDF --
def generate_salt(length: int) -> bytes: ...
def derive_key_argon2(
    passphrase: bytes,
    salt: bytes,
    m_cost: int = 65536,
    t_cost: int = 3,
    p_cost: int = 1,
) -> bytes: ...
def derive_key_scrypt(
    passphrase: bytes,
    salt: bytes,
    log_n: int = 15,
    r: int = 8,
    p: int = 1,
) -> bytes: ...

# -- RSA --
def rsa_generate(bits: int) -> tuple[str, str]: ...
def rsa_encrypt(public_pem: str, plaintext: bytes) -> bytes: ...
def rsa_decrypt(private_pem: str, ciphertext: bytes) -> bytes: ...
def rsa_sign(private_pem: str, message: bytes) -> bytes: ...
def rsa_verify(public_pem: str, message: bytes, signature: bytes) -> bool: ...
def rsa_fingerprint(public_pem: str) -> str: ...

# -- Ed25519 --
def ed25519_generate() -> tuple[str, str]: ...
def ed25519_sign(signing_pem: str, message: bytes) -> bytes: ...
def ed25519_verify(verifying_pem: str, message: bytes, signature: bytes) -> bool: ...
def ed25519_fingerprint(verifying_pem: str) -> str: ...

# -- X25519 --
def x25519_generate() -> tuple[bytes, bytes]: ...
def x25519_encrypt_key_agreement(their_public: bytes) -> tuple[bytes, bytes]: ...
def x25519_decrypt_key_agreement(secret_raw: bytes, ephemeral_public: bytes) -> bytes: ...
def x25519_fingerprint(public_raw: bytes) -> str: ...

# -- OpenPGP --
def pgp_generate(user_id: str) -> tuple[str, str]: ...
def pgp_encrypt(plaintext: bytes, recipient_public_keys: list[str]) -> bytes: ...
def pgp_decrypt(ciphertext: bytes, secret_key_armored: str) -> bytes: ...
def pgp_sign(message: bytes, secret_key_armored: str) -> bytes: ...
def pgp_verify(signed_message: bytes, public_key_armored: str) -> tuple[bytes, bool]: ...
def pgp_fingerprint(armored_key: str) -> str: ...
def pgp_user_id(armored_key: str) -> Optional[str]: ...

# -- HBZF file encryption --
def encrypt_data(
    plaintext: bytes,
    algorithm: str = "aes",
    wrapping: str = "password",
    passphrase: Optional[bytes] = None,
    recipient_public_pem: Optional[str] = None,
    recipient_public_raw: Optional[bytes] = None,
) -> bytes: ...
def decrypt_data(
    data: bytes,
    passphrase: Optional[bytes] = None,
    private_pem: Optional[str] = None,
    secret_raw: Optional[bytes] = None,
) -> bytes: ...
def encrypt_file(
    input_path: str,
    output_path: str,
    algorithm: str = "aes",
    wrapping: str = "password",
    passphrase: Optional[bytes] = None,
    recipient_public_pem: Optional[str] = None,
    recipient_public_raw: Optional[bytes] = None,
) -> int: ...
def decrypt_file(
    input_path: str,
    output_path: str,
    passphrase: Optional[bytes] = None,
    private_pem: Optional[str] = None,
    secret_raw: Optional[bytes] = None,
) -> int: ...

# -- Utilities --
def compute_fingerprint(public_key_bytes: bytes) -> str: ...
def detect_key_format(data: bytes) -> str: ...

# -- Classes --
class KeyMetadata:
    fingerprint: str
    algorithm: str
    label: str
    created_at: str
    has_private: bool
    has_public: bool
    def __repr__(self) -> str: ...

class Contact:
    name: str
    email: Optional[str]
    key_fingerprints: list[str]
    notes: Optional[str]
    created_at: str
    def __repr__(self) -> str: ...

class KeyStore:
    def __init__(self, path: Optional[str] = None) -> None: ...
    @property
    def base_path(self) -> str: ...
    def store_private_key(
        self,
        fingerprint: str,
        key_bytes: bytes,
        passphrase: bytes,
        algorithm: str,
        label: str,
    ) -> None: ...
    def store_public_key(
        self,
        fingerprint: str,
        key_bytes: bytes,
        algorithm: str,
        label: str,
    ) -> None: ...
    def load_private_key(self, fingerprint: str, passphrase: bytes) -> bytes: ...
    def load_public_key(self, fingerprint: str) -> bytes: ...
    def list_keys(self) -> list[KeyMetadata]: ...
    def get_key_metadata(self, fingerprint: str) -> Optional[KeyMetadata]: ...
    def find_keys_by_label(self, query: str) -> list[KeyMetadata]: ...
    def delete_key(self, fingerprint: str) -> None: ...
    def add_contact(
        self,
        name: str,
        email: Optional[str] = None,
        notes: Optional[str] = None,
    ) -> None: ...
    def associate_key_with_contact(self, contact_name: str, fingerprint: str) -> None: ...
    def get_contact(self, name: str) -> Optional[Contact]: ...
    def list_contacts(self) -> list[Contact]: ...
    def remove_contact(self, name: str) -> None: ...
    def resolve_recipient(self, name_or_fp: str) -> list[str]: ...
